apiVersion: v1
kind: Secret
metadata:
  name: logging-loki-s3
stringData:
  endpoint: http://minio-service.minio.svc:9000
  bucketnames: loki-storage
  access_key_id: minioadmin
  access_key_secret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
type: Opaque