apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: eap74-openjdk11-openshift-rhel8
spec:
  lookupPolicy:
    local: false
  tags:
  - from:
      kind: DockerImage
      name: registry.redhat.io/jboss-eap-7/eap74-openjdk11-openshift-rhel8
    generation: 1
    importPolicy:
      importMode: Legacy
    name: latest
    referencePolicy:
      type: Source