apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: distributed-tracing
spec:
  type: DistributedTracing
  # Configuration for the distributed tracing console plugin.
  distributedTracing:
    # Maximum duration before a query timeout.
    timeout: 30s