apiVersion: v1
kind: Secret
metadata:
  name: minio-tempo
stringData:
  endpoint: http://minio-service.minio.svc:9000
  bucket: tempo
  access_key_id: minioadmin
  access_key_secret: zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG
type: Opaque