apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"cargo-app:latest","namespace":"proa"},"fieldPath":"spec.template.spec.containers[?(@.name==\"cargo-app\")].image","paused":"false"}]'
  labels:
    app: cargo-app-secret
  name: cargo-app-secret
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cargo-app-secret
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cargo-app-secret
        deployment: cargo-app-secret
    spec:
      containers:
      - image: cargo-app-postgres:latest
        imagePullPolicy: IfNotPresent
        name: cargo-app-secretenv
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: CARGO_POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: cargo-secret
              key: CARGO_POSTGRES_HOST
        - name: CARGO_POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: cargo-secret
              key: CARGO_POSTGRES_PORT
        - name: CARGO_POSTGRES_NAME
          valueFrom:
            secretKeyRef:
              name: cargo-secret
              key: CARGO_POSTGRES_NAME
        - name: CARGO_POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: cargo-secret
              key: CARGO_POSTGRES_USERNAME              
        - name: CARGO_POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: cargo-secret
              key: CARGO_POSTGRES_PASSWORD              
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30