apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    alpha.image.policy.openshift.io/resolve-names: '*'
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"cargo-app:latest","namespace":"proa"},"fieldPath":"spec.template.spec.containers[?(@.name==\"cargo-app\")].image","paused":"false"}]'
  labels:
    app: cargo-app-pvc
  name: cargo-app-pvc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: cargo-app-pvc
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: cargo-app-pvc
        deployment: cargo-app-pvc
    spec:
      containers:
      - image: cargo-app:latest
        imagePullPolicy: IfNotPresent
        name: cargo-app-pvc
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        - containerPort: 8778
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /mydata
          name: cargo-volume
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - persistentVolumeClaim:
          claimName: cargo-claim
        name: cargo-volume